package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

/* JADX INFO: loaded from: classes.dex */
public final class zzd {
    public final String name;
    public final String zzcd;
    public final String zzci;
    public final String zzmc;
    public final String zzmd;
    public final String zzme;
    public final String zzmf;
    public final String zzmg;
    public final String zzmh;
    public final String zzmi;
    public final String zzmj;
    public final String zzmk;
    public final String zzml;
    public final String zzmm;
    public final String zzmn;
    public final String zzmo;
    public final String zzmp;
    public final String zzmq;
    public final String zzmr;
    private final String zzms;
    public final String zzmt;
    public final String zzmu;
    public final String zzmv;
    public final String zzmw;
    public final String zzmx;
    public final String zzmy;
    public final String zzmz;
    public final String zzna;
    public final String zznb;
    public final String zznc;
    public final String zznd;
    public final String zzne;
    public final String zznf;
    public final String zzng;
    public final String zznh;
    public final String zzni;

    public zzd(String str) {
        String strConcat;
        if (TextUtils.isEmpty(str)) {
            this.zzmc = "external_player_id";
            this.zzmd = "profile_name";
            this.zzme = "profile_icon_image_uri";
            this.zzmf = "profile_icon_image_url";
            this.zzmg = "profile_hi_res_image_uri";
            this.zzmh = "profile_hi_res_image_url";
            this.zzmi = "last_updated";
            this.zzmj = "is_in_circles";
            this.zzmk = "played_with_timestamp";
            this.zzml = "current_xp_total";
            this.zzmm = "current_level";
            this.zzmn = "current_level_min_xp";
            this.zzmo = "current_level_max_xp";
            this.zzmp = "next_level";
            this.zzmq = "next_level_max_xp";
            this.zzmr = "last_level_up_timestamp";
            this.zzcd = "player_title";
            this.zzms = "has_all_public_acls";
            this.zzmt = "is_profile_visible";
            this.zzmu = "most_recent_external_game_id";
            this.zzmv = "most_recent_game_name";
            this.zzmw = "most_recent_activity_timestamp";
            this.zzmx = "most_recent_game_icon_uri";
            this.zzmy = "most_recent_game_hi_res_uri";
            this.zzmz = "most_recent_game_featured_uri";
            this.zzna = "has_debug_access";
            this.zzci = "gamer_tag";
            this.name = "real_name";
            this.zznb = "banner_image_landscape_uri";
            this.zznc = "banner_image_landscape_url";
            this.zznd = "banner_image_portrait_uri";
            this.zzne = "banner_image_portrait_url";
            this.zznf = "gamer_friend_status";
            this.zzng = "gamer_friend_update_timestamp";
            this.zznh = "is_muted";
            strConcat = "total_unlocked_achievements";
        } else {
            String strValueOf = String.valueOf(str);
            String strValueOf2 = String.valueOf("external_player_id");
            this.zzmc = strValueOf2.length() != 0 ? strValueOf.concat(strValueOf2) : new String(strValueOf);
            String strValueOf3 = String.valueOf(str);
            String strValueOf4 = String.valueOf("profile_name");
            this.zzmd = strValueOf4.length() != 0 ? strValueOf3.concat(strValueOf4) : new String(strValueOf3);
            String strValueOf5 = String.valueOf(str);
            String strValueOf6 = String.valueOf("profile_icon_image_uri");
            this.zzme = strValueOf6.length() != 0 ? strValueOf5.concat(strValueOf6) : new String(strValueOf5);
            String strValueOf7 = String.valueOf(str);
            String strValueOf8 = String.valueOf("profile_icon_image_url");
            this.zzmf = strValueOf8.length() != 0 ? strValueOf7.concat(strValueOf8) : new String(strValueOf7);
            String strValueOf9 = String.valueOf(str);
            String strValueOf10 = String.valueOf("profile_hi_res_image_uri");
            this.zzmg = strValueOf10.length() != 0 ? strValueOf9.concat(strValueOf10) : new String(strValueOf9);
            String strValueOf11 = String.valueOf(str);
            String strValueOf12 = String.valueOf("profile_hi_res_image_url");
            this.zzmh = strValueOf12.length() != 0 ? strValueOf11.concat(strValueOf12) : new String(strValueOf11);
            String strValueOf13 = String.valueOf(str);
            String strValueOf14 = String.valueOf("last_updated");
            this.zzmi = strValueOf14.length() != 0 ? strValueOf13.concat(strValueOf14) : new String(strValueOf13);
            String strValueOf15 = String.valueOf(str);
            String strValueOf16 = String.valueOf("is_in_circles");
            this.zzmj = strValueOf16.length() != 0 ? strValueOf15.concat(strValueOf16) : new String(strValueOf15);
            String strValueOf17 = String.valueOf(str);
            String strValueOf18 = String.valueOf("played_with_timestamp");
            this.zzmk = strValueOf18.length() != 0 ? strValueOf17.concat(strValueOf18) : new String(strValueOf17);
            String strValueOf19 = String.valueOf(str);
            String strValueOf20 = String.valueOf("current_xp_total");
            this.zzml = strValueOf20.length() != 0 ? strValueOf19.concat(strValueOf20) : new String(strValueOf19);
            String strValueOf21 = String.valueOf(str);
            String strValueOf22 = String.valueOf("current_level");
            this.zzmm = strValueOf22.length() != 0 ? strValueOf21.concat(strValueOf22) : new String(strValueOf21);
            String strValueOf23 = String.valueOf(str);
            String strValueOf24 = String.valueOf("current_level_min_xp");
            this.zzmn = strValueOf24.length() != 0 ? strValueOf23.concat(strValueOf24) : new String(strValueOf23);
            String strValueOf25 = String.valueOf(str);
            String strValueOf26 = String.valueOf("current_level_max_xp");
            this.zzmo = strValueOf26.length() != 0 ? strValueOf25.concat(strValueOf26) : new String(strValueOf25);
            String strValueOf27 = String.valueOf(str);
            String strValueOf28 = String.valueOf("next_level");
            this.zzmp = strValueOf28.length() != 0 ? strValueOf27.concat(strValueOf28) : new String(strValueOf27);
            String strValueOf29 = String.valueOf(str);
            String strValueOf30 = String.valueOf("next_level_max_xp");
            this.zzmq = strValueOf30.length() != 0 ? strValueOf29.concat(strValueOf30) : new String(strValueOf29);
            String strValueOf31 = String.valueOf(str);
            String strValueOf32 = String.valueOf("last_level_up_timestamp");
            this.zzmr = strValueOf32.length() != 0 ? strValueOf31.concat(strValueOf32) : new String(strValueOf31);
            String strValueOf33 = String.valueOf(str);
            String strValueOf34 = String.valueOf("player_title");
            this.zzcd = strValueOf34.length() != 0 ? strValueOf33.concat(strValueOf34) : new String(strValueOf33);
            String strValueOf35 = String.valueOf(str);
            String strValueOf36 = String.valueOf("has_all_public_acls");
            this.zzms = strValueOf36.length() != 0 ? strValueOf35.concat(strValueOf36) : new String(strValueOf35);
            String strValueOf37 = String.valueOf(str);
            String strValueOf38 = String.valueOf("is_profile_visible");
            this.zzmt = strValueOf38.length() != 0 ? strValueOf37.concat(strValueOf38) : new String(strValueOf37);
            String strValueOf39 = String.valueOf(str);
            String strValueOf40 = String.valueOf("most_recent_external_game_id");
            this.zzmu = strValueOf40.length() != 0 ? strValueOf39.concat(strValueOf40) : new String(strValueOf39);
            String strValueOf41 = String.valueOf(str);
            String strValueOf42 = String.valueOf("most_recent_game_name");
            this.zzmv = strValueOf42.length() != 0 ? strValueOf41.concat(strValueOf42) : new String(strValueOf41);
            String strValueOf43 = String.valueOf(str);
            String strValueOf44 = String.valueOf("most_recent_activity_timestamp");
            this.zzmw = strValueOf44.length() != 0 ? strValueOf43.concat(strValueOf44) : new String(strValueOf43);
            String strValueOf45 = String.valueOf(str);
            String strValueOf46 = String.valueOf("most_recent_game_icon_uri");
            this.zzmx = strValueOf46.length() != 0 ? strValueOf45.concat(strValueOf46) : new String(strValueOf45);
            String strValueOf47 = String.valueOf(str);
            String strValueOf48 = String.valueOf("most_recent_game_hi_res_uri");
            this.zzmy = strValueOf48.length() != 0 ? strValueOf47.concat(strValueOf48) : new String(strValueOf47);
            String strValueOf49 = String.valueOf(str);
            String strValueOf50 = String.valueOf("most_recent_game_featured_uri");
            this.zzmz = strValueOf50.length() != 0 ? strValueOf49.concat(strValueOf50) : new String(strValueOf49);
            String strValueOf51 = String.valueOf(str);
            String strValueOf52 = String.valueOf("has_debug_access");
            this.zzna = strValueOf52.length() != 0 ? strValueOf51.concat(strValueOf52) : new String(strValueOf51);
            String strValueOf53 = String.valueOf(str);
            String strValueOf54 = String.valueOf("gamer_tag");
            this.zzci = strValueOf54.length() != 0 ? strValueOf53.concat(strValueOf54) : new String(strValueOf53);
            String strValueOf55 = String.valueOf(str);
            String strValueOf56 = String.valueOf("real_name");
            this.name = strValueOf56.length() != 0 ? strValueOf55.concat(strValueOf56) : new String(strValueOf55);
            String strValueOf57 = String.valueOf(str);
            String strValueOf58 = String.valueOf("banner_image_landscape_uri");
            this.zznb = strValueOf58.length() != 0 ? strValueOf57.concat(strValueOf58) : new String(strValueOf57);
            String strValueOf59 = String.valueOf(str);
            String strValueOf60 = String.valueOf("banner_image_landscape_url");
            this.zznc = strValueOf60.length() != 0 ? strValueOf59.concat(strValueOf60) : new String(strValueOf59);
            String strValueOf61 = String.valueOf(str);
            String strValueOf62 = String.valueOf("banner_image_portrait_uri");
            this.zznd = strValueOf62.length() != 0 ? strValueOf61.concat(strValueOf62) : new String(strValueOf61);
            String strValueOf63 = String.valueOf(str);
            String strValueOf64 = String.valueOf("banner_image_portrait_url");
            this.zzne = strValueOf64.length() != 0 ? strValueOf63.concat(strValueOf64) : new String(strValueOf63);
            String strValueOf65 = String.valueOf(str);
            String strValueOf66 = String.valueOf("gamer_friend_status");
            this.zznf = strValueOf66.length() != 0 ? strValueOf65.concat(strValueOf66) : new String(strValueOf65);
            String strValueOf67 = String.valueOf(str);
            String strValueOf68 = String.valueOf("gamer_friend_update_timestamp");
            this.zzng = strValueOf68.length() != 0 ? strValueOf67.concat(strValueOf68) : new String(strValueOf67);
            String strValueOf69 = String.valueOf(str);
            String strValueOf70 = String.valueOf("is_muted");
            this.zznh = strValueOf70.length() != 0 ? strValueOf69.concat(strValueOf70) : new String(strValueOf69);
            String strValueOf71 = String.valueOf(str);
            String strValueOf72 = String.valueOf("total_unlocked_achievements");
            strConcat = strValueOf72.length() != 0 ? strValueOf71.concat(strValueOf72) : new String(strValueOf71);
        }
        this.zzni = strConcat;
    }
}
