#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import struct
from collections import Counter
from pathlib import Path

from capstone import Cs, CS_ARCH_ARM64, CS_MODE_ARM

BIAS = 0x10000000
MMAP_LO = 0x5100000000
MMAP_HI = 0x5140000000
SYSCALL_NAMES = {
    26:'inotify_init1', 27:'inotify_add_watch', 56:'openat', 57:'close',
    61:'getdents64', 62:'lseek', 63:'read', 64:'write', 78:'readlinkat',
    79:'newfstatat', 117:'ptrace', 129:'kill', 167:'prctl', 172:'getpid',
    215:'munmap', 222:'mmap', 226:'mprotect', 260:'wait4',
}


def insns(data: bytes, addr: int, limit: int = 128):
    md = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
    out=[]
    for ins in md.disasm(data[:limit], addr):
        out.append({'address':ins.address,'mnemonic':ins.mnemonic,'op_str':ins.op_str})
        if ins.mnemonic in ('ret','br') or len(out)>=32:
            break
    return out


def parse_syscall(rows):
    nr=None
    for r in rows:
        if r['mnemonic'] in ('mov','movz') and r['op_str'].startswith(('x8, #','w8, #')):
            try: nr=int(r['op_str'].split('#',1)[1],0)
            except ValueError: pass
        if r['mnemonic']=='svc':
            return {'nr':nr,'name':SYSCALL_NAMES.get(nr, f'sys_{nr}' if nr is not None else None)}
    return None


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--emulation-dir',type=Path,required=True)
    ap.add_argument('--out',type=Path,required=True)
    a=ap.parse_args()
    report=json.loads((a.emulation_dir/'dt-init-emulation-svc.json').read_text())
    snap=next(x for x in report['snapshots'] if x['label']=='asm-table-complete')
    builder=next(x for x in report['snapshots'] if x['label']=='builder-entry')
    cfg=(a.emulation_dir/'runtime-config-at-builder.bin').read_bytes()
    rwx=(a.emulation_dir/'rwx-page-asm-table-complete.bin').read_bytes()
    rwx_base=snap['rwx_page_ptr']
    count=struct.unpack_from('<I',cfg,0x70)[0]
    descriptors=[]
    for i in range(count):
        off=0x74+i*12
        if off+12>len(cfg): break
        v=struct.unpack_from('<III',cfg,off)
        descriptors.append({'index':i,'offset':off,'u32_0':v[0],'u32_4':v[1],'u32_8':v[2]})

    slots=[]
    for idx,p in enumerate(snap['asmfunction_table']):
        row={'slot':idx,'field':idx*8,'pointer':p}
        if rwx_base <= p < rwx_base+len(rwx):
            row['class']='rwx-generated'
            roff=p-rwx_base
            row['rwx_offset']=roff
            dis=insns(rwx[roff:],p)
            row['instructions']=dis
            row['syscall']=parse_syscall(dis)
        elif BIAS <= p < BIAS+0x3000000:
            row['class']='libcompatible-internal'
            row['relative']=p-BIAS
        elif MMAP_LO <= p < MMAP_HI:
            row['class']='other-mmap'
        elif p==0:
            row['class']='zero'
        else:
            row['class']='other'
        slots.append(row)

    ptr_counts=Counter(x['pointer'] for x in slots if x['pointer'])
    generated=sorted((x for x in slots if x['class']=='rwx-generated'),key=lambda x:x['rwx_offset'])
    result={
        'runtime_config':{
            'count':count,
            'descriptor_count_parsed':len(descriptors),
            'descriptors':descriptors,
            'config_sha256':builder.get('config_sha256'),
        },
        'rwx':{
            'base':rwx_base,
            'size':len(rwx),
            'nonzero_bytes':snap.get('rwx_page_nonzero_bytes'),
        },
        'slots':slots,
        'unique_nonzero_pointers':len(ptr_counts),
        'duplicate_pointers':{hex(k):v for k,v in ptr_counts.items() if v>1},
    }
    a.out.mkdir(parents=True,exist_ok=True)
    (a.out/'runtime-trampoline-analysis.json').write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n')

    L=['# Runtime AppGuard trampoline reconstruction','',
       f'- runtime descriptor count: **{count}**',
       f'- parsed descriptors: **{len(descriptors)}**',
       f'- generated RWX page: `{rwx_base:#x}` / {len(rwx)} bytes',
       f'- nonzero generated bytes: **{snap.get("rwx_page_nonzero_bytes")}**','',
       '## 18 runtime descriptors','',
       '| # | +0 | +4 | +8 |','|---:|---:|---:|---:|']
    for d in descriptors:
        L.append(f"| {d['index']} | `0x{d['u32_0']:x}` | `0x{d['u32_4']:x}` | `0x{d['u32_8']:x}` |")
    L += ['', '## asmFunction dispatch slots','',
          '| Slot | Field | Pointer | Class | Generated offset | Syscall |','|---:|---:|---:|---|---:|---|']
    for s in slots:
        sc=s.get('syscall') or {}
        L.append(f"| {s['slot']} | `+0x{s['field']:x}` | `{s['pointer']:#x}` | {s['class']} | " +
                 (f"`+0x{s['rwx_offset']:x}`" if 'rwx_offset' in s else '-') + ' | ' +
                 (f"`{sc.get('nr')}` {sc.get('name')}" if sc else '-') + ' |')
    L += ['', '## Generated trampoline disassembly','']
    for s in generated:
        L += [f"### slot {s['slot']} / `+0x{s['field']:x}` → RWX `+0x{s['rwx_offset']:x}`",'', '```asm']
        for i in s['instructions']:
            L.append(f"0x{i['address']:x}: {i['mnemonic']} {i['op_str']}")
        L += ['```','']
    (a.out/'runtime-trampoline-analysis.md').write_text('\n'.join(L)+'\n')
    print(json.dumps({'count':count,'slots':[(s['slot'],s['class'],s.get('rwx_offset'),s.get('syscall')) for s in slots]},indent=2))

if __name__=='__main__': main()
